---
schema_version: 1
name: fa_q256_kv1024_d128
operator: flash_attention_v2
attention:
    q: 256
    kv: 1024
    d: 128
    batch: 1
    heads: 1
    input_dtype: int8
    accumulation_dtype: int32
    softmax_dtype: float32
tiling:
    q: 128
    kv: 128
