# -*- mode:python -*-

Import('*')

DebugFlag('MegaCmdQueue')
DebugFlag('SpecializedExecutionUnit')
DebugFlag('DmaUnit')
DebugFlag('ScratchpadMemory')
DebugFlag('VPU')

SimObject('LutUnit.py', sim_objects=['LutUnit'])
SimObject('MegaCmdQueue.py', sim_objects=['MegaCmdQueue'])
SimObject('SpecializedExecutionUnit.py',
          sim_objects=['SpecializedExecutionUnit'])
SimObject('VpuUnit.py', sim_objects=['VpuUnit'])
SimObject('ScratchpadMemory.py', sim_objects=['ScratchpadMemory'])
Source('LutUnit.cc')
Source('MegaCmdQueue.cc')
Source('SpecializedExecutionUnit.cc')
Source('VpuUnit.cc')
Source('ScratchpadMemory.cc')
