# -*- mode:python -*-

Import('*')

DebugFlag('MegaCmdQueue')
DebugFlag('SpecializedExecutionUnit')
DebugFlag('ScratchpadMemory')

SimObject('MegaCmdQueue.py', sim_objects=['MegaCmdQueue'])
SimObject('SpecializedExecutionUnit.py',
          sim_objects=['SpecializedExecutionUnit'])
SimObject('ScratchpadMemory.py', sim_objects=['ScratchpadMemory'])
Source('MegaCmdQueue.cc')
Source('SpecializedExecutionUnit.cc')
Source('ScratchpadMemory.cc')
